name: CI

on:
  push:
    branches: [main, v2]
  pull_request:
    branches: [main, v2]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libgles-dev libpulse-dev libxext-dev

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Workaround Zig 0.16.0 ZIP unpack failure
        # https://codeberg.org/ziglang/zig/issues/31964
        shell: bash
        run: mkdir -p "${ZIG_GLOBAL_CACHE_DIR}/tmp"

      - name: Check Formatting
        run: zig fmt --ast-check --check .

      - name: Build
        run: zig build --summary all
